---
- name: Verify postgresql 10 is installed
  stat:
    path: /var/lib/pgsql/10/data/PG_VERSION
  register: pg_version
  failed_when: pg_version.stat.exists == False
  changed_when: False

- name: Install postgresql 10 yum repository
  package:
    name: "{{ pgstattuple_postgresql_10_repo_url }}"
    state: present

- name: Install postgresql10-contrib for postgresql 10
  package:
    name: postgresql10-contrib
    state: present

- name: Get a list of postgresql extension
  shell: psql -c "SELECT * FROM pg_extension;"
  args:
    executable: /bin/bash
  register: postgresql_plugin_list
  become: yes
  become_user: postgres
  become_method: sudo
  changed_when: False

- name: Enable the pg_partman extension
  shell: "psql -c \"CREATE EXTENSION pgstattuple;\""
  args:
    executable: /bin/bash
  register: enable_pgstattuple
  become: yes
  become_user: postgres
  become_method: sudo
  failed_when: '"CREATE EXTENSION" not in enable_pgstattuple.stdout'
  changed_when: False
  when:
  - '"pgstattuple" not in postgresql_plugin_list.stdout'